name: aurora_mobile_engineer_take_home
description: "Aurora Mobile Engineer Take-Home"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dio: ^5.9.0
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.3.1
  palette_generator: ^0.3.3+3
  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.5
  logger: ^2.6.1
  get_it: ^8.2.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  json_annotation: ^4.9.0
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  json_serializable: ^6.11.1
  freezed: ^3.2.3
  bloc_test: ^10.0.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
